updateVimMapCommand(';', 'ex', 'normal')
updateVimMapCommand2(':', 'motion', 'repeatLastCharacterSearch', { forward: true })
updateVimMapCommand('H', 'motion', 'moveToFirstNonWhiteSpaceCharacter')
updateVimMapCommand('L', 'motion', 'moveToEol')
updateVimMapCommand2('gj', 'motion', 'moveByLines', { forward: true, linewise: true })
updateVimMapCommand2('gk', 'motion', 'moveByLines', { forward: false, linewise: true })
updateVimMapCommand2('j', 'motion', 'moveByDisplayLines', { forward: true })
updateVimMapCommand2('k', 'motion', 'moveByDisplayLines', { forward: false })
updateVimMap('J', '10j', 'normal')
updateVimMap('K', '10k', 'normal')
updateVimMap('jj', '<Esc>', 'insert')
updateVimMap('<Space>,', '<<', 'visual')
updateVimMap('<Space>.', '>>', 'visual')
